---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.10.4

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[gesto-java::default]
    attributes: